spring.application.name=Employee_Salary_Management_using_Query

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=subrat
spring.datasource.password=67890

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update