spring.application.name=BootIOJproj5_Product_Catalog_System

st.subrat.products[0].id=1
st.subrat.products[0].name=Laptop
st.subrat.products[0].price=60000
st.subrat.products[1].id=2
st.subrat.products[1].name=Mobile
st.subrat.products[1].price=20000
st.subrat.products[2].id=3
st.subrat.products[2].name=Tablet
st.subrat.products[2].price=15000
