spring.application.name=Employee_Configuration_System

emp.info.id=1
emp.info.name=subrat
emp.info.salary=500000
emp.info.skills[0]=JAVA
emp.info.skills[1]=CSS
emp.info.skills[2]=HTML
emp.info.skills[3]=SPRINGBOOK

emp.info.plist[0]=nuclear
emp.info.plist[1]=world war
emp.info.plist[2]=wrath of god

emp.info.tools[0]=j2ee
emp.info.tools[1]=lambok
emp.info.tools[2]=jdbc
emp.info.tools[3]=servlet

emp.info.experience.java=3
emp.info.experience.springboot=4

emp.info.address.city=telengana
emp.info.address.state=hyd
emp.info.address.pincode=789
