spring.application.name=BootIOJproj4_Company_Department_List_System
#department
dep.subrat.dept[0].deptId=1
dep.subrat.dept[0].deptName=HR
dep.subrat.dept[1].deptId=2
dep.subrat.dept[1].deptName=IT
dep.subrat.dept[2].deptId=3
dep.subrat.dept[2].deptName=FINANCE


