spring.application.name=Travel_Booking_Management_System


spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=subrat
spring.datasource.password=67890

spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.keepalive-time=100000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update